### ISSUE TITLE
Flink runner not supported for scala 2.13

### ISSUE THREAD

**Issue by kristapsveveris** [spotify/scio.g8#71]
```zsh
[error] sbt.librarymanagement.ResolveException: Error downloading org.apache.flink:flink-runtime_2.13:1.9.1
[error]   Not found
[error]   Not found
[error]   not found: /Users/kristapsveveris/.ivy2/local/org.apache.flink/flink-runtime_2.13/1.9.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/apache/flink/flink-runtime_2.13/1.9.1/flink-runtime_2.13-1.9.1.pom
[error] Error downloading org.apache.flink:flink-streaming-java_2.13:1.9.1
[error]   Not found
[error]   Not found
[error]   not found: /Users/kristapsveveris/.ivy2/local/org.apache.flink/flink-streaming-java_2.13/1.9.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/apache/flink/flink-streaming-java_2.13/1.9.1/flink-streaming-java_2.13-1.9.1.pom
[error] Error downloading org.apache.flink:flink-clients_2.13:1.9.1
[error]   Not found
[error]   Not found
[error]   not found: /Users/kristapsveveris/.ivy2/local/org.apache.flink/flink-clients_2.13/1.9.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/apache/flink/flink-clients_2.13/1.9.1/flink-clients_2.13-1.9.1.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:249)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$35(CoursierDependencyResolution.scala:218)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:218)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2950)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:830)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.apache.flink:flink-runtime_2.13:1.9.1
[error]   Not found
[error]   Not found
[error]   not found: /Users/kristapsveveris/.ivy2/local/org.apache.flink/flink-runtime_2.13/1.9.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/apache/flink/flink-runtime_2.13/1.9.1/flink-runtime_2.13-1.9.1.pom
[error] Error downloading org.apache.flink:flink-streaming-java_2.13:1.9.1
[error]   Not found
[error]   Not found
[error]   not found: /Users/kristapsveveris/.ivy2/local/org.apache.flink/flink-streaming-java_2.13/1.9.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/apache/flink/flink-streaming-java_2.13/1.9.1/flink-streaming-java_2.13-1.9.1.pom
[error] Error downloading org.apache.flink:flink-clients_2.13:1.9.1
[error]   Not found
[error]   Not found
[error]   not found: /Users/kristapsveveris/.ivy2/local/org.apache.flink/flink-clients_2.13/1.9.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/apache/flink/flink-clients_2.13/1.9.1/flink-clients_2.13-1.9.1.pom
```

**Comment by nevillelyh** [comment]
https://mvnrepository.com/artifact/org.apache.flink/flink-runtime
Flink is still only published for 2.11 + 2.12 as of 1.10.1 so don't think there's anything we can do right now.
